version: "3.7"
services:
  db:
    image: "mariadb:latest"
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: miru
      MARIADB_USER: leo
      MARIADB_PASSWORD: leo
      MARIADB_ROOT_PASSWORD: leo
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: "adminer"
    ports:
      - 8080:8080

volumes:
  dbdata:
    driver: local
